import { fetchByOptionBuilder, safeResponseOutput } from "@helper/fetcher";
import { QueryOptionBuilder, type QueryOptions } from "@helper/query_options";
import type { mirrornode } from "$types";
import type { BalancesResponse } from "../../openapi/types";

type Options = {
  /**
   * The optional balance value to compare against
   */
  "account.balance"?: string;
  /**
   * Account id or account alias with no shard realm or evm address with no shard realm
   */
  "account.id"?: string;
  /**
   * The account's public key to compare against
   */
  "account.publickey"?: string;
  /**
   * The maximum number of items to return
   */
  limit?: number;
  /**
   * The order in which items are listed
   */
  order?: mirrornode.orderQueryParam;
  /**
   * The consensus timestamp as a Unix timestamp in seconds.nanoseconds format with an
   * optional comparison operator. See [unixtimestamp.com](https://www.unixtimestamp.com/) for
   * a simple way to convert a date to the 'seconds' part of the Unix time.
   */
  timestamp?: string[];
  [property: string]: unknown;
};

/**
Returns a list of account and token balances on the network.

Balance information returned by this API has a 15 minute granularity as it's generated by an asynchronous balance snapshot process.

This information is limited to at most 50 token balances per account as outlined in HIP-367.

As such, it's not recommended for general use and we instead recommend using either `/api/v1/accounts/{id}/tokens` or `/api/v1/tokens/{id}/balances` to obtain the current token balance information and `/api/v1/accounts/{id}` to return the current account balance.
*/
export async function listAccountBalances(options?: QueryOptions<Options>) {
  const opBuilder = new QueryOptionBuilder(options);

  const res = await fetchByOptionBuilder("/api/v1/balances", opBuilder);

  return safeResponseOutput<BalancesResponse>(res);
}
